//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTransferService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GXX_DS_0403Entities : DbContext
    {
        public GXX_DS_0403Entities()
            : base("name=GXX_DS_0403Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountTypes> AccountTypes { get; set; }
        public virtual DbSet<Bug> Bug { get; set; }
        public virtual DbSet<BugTypes> BugTypes { get; set; }
        public virtual DbSet<CustomerFieldTrackExt> CustomerFieldTrackExt { get; set; }
        public virtual DbSet<CustomerFieldTrackExt2> CustomerFieldTrackExt2 { get; set; }
        public virtual DbSet<IssueTypes> IssueTypes { get; set; }
        public virtual DbSet<LogIn> LogIn { get; set; }
        public virtual DbSet<ProductStatusTypes> ProductStatusTypes { get; set; }
        public virtual DbSet<SubProject> SubProject { get; set; }
        public virtual DbSet<SubProjectOwners> SubProjectOwners { get; set; }
        public virtual DbSet<SubProjectTree> SubProjectTree { get; set; }
        public virtual DbSet<BugSelectionInfo> BugSelectionInfo { get; set; }
        public virtual DbSet<ProjectMembers> ProjectMembers { get; set; }
    }
}
