//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTransferService
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueTypes
    {
        public int ProjectID { get; set; }
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> TypeCategory { get; set; }
        public Nullable<int> ChildOption { get; set; }
        public Nullable<int> ParentCategory { get; set; }
        public Nullable<int> WorkflowID { get; set; }
        public string ReadOnlyFields { get; set; }
        public Nullable<int> SupportOnBehalfOf { get; set; }
        public Nullable<int> IfAttachFormToSubmissionEWP { get; set; }
        public Nullable<int> SelectedEventTemplate { get; set; }
        public Nullable<int> SelectedAttachedForm { get; set; }
        public Nullable<int> DisplayFormOption { get; set; }
        public string DisplayOptionLabel { get; set; }
        public Nullable<int> EnableCalendarView { get; set; }
        public Nullable<int> EnablePlanningView { get; set; }
        public Nullable<int> IfWarningForConflict { get; set; }
        public Nullable<int> SystemTypeID { get; set; }
        public Nullable<int> IconIndex { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> SpaceTypeOption { get; set; }
        public Nullable<int> MilestoneFolderAutoCreateOption { get; set; }
        public Nullable<int> MilestoneChangeOption { get; set; }
        public Nullable<int> MSFolderCreateOption { get; set; }
        public Nullable<int> AutoCreateOption { get; set; }
        public Nullable<int> ResourceAssignmentOption { get; set; }
    }
}
