//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTransferService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStatusTypes
    {
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> IfClosed { get; set; }
        public Nullable<int> CanAddVersion { get; set; }
        public Nullable<int> CanAddBuild { get; set; }
        public Nullable<int> CanAddDevelop { get; set; }
        public Nullable<int> CanAddSpec { get; set; }
        public Nullable<int> HSCompanyID { get; set; }
    }
}
