//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTransferService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMembers
    {
        public int ProjectID { get; set; }
        public int MemberID { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public Nullable<int> IsCrntLogon { get; set; }
        public Nullable<System.DateTime> LastTimeOn { get; set; }
        public string ListViewColumns { get; set; }
        public Nullable<int> IsInactiveMember { get; set; }
        public Nullable<int> DefaultUserSelection { get; set; }
        public Nullable<int> LastUserListID { get; set; }
        public Nullable<int> IsFromWeb { get; set; }
        public Nullable<int> EmailReplyAccount { get; set; }
        public string FOPersonalEmail { get; set; }
        public Nullable<int> Enable2SelectEmailAddress { get; set; }
        public Nullable<int> EmailReplyOption { get; set; }
        public Nullable<int> InventoryLocationID { get; set; }
        public string PreferedUserIDs { get; set; }
    }
}
